#binary_sensor:
#  - platform: homeassistant
#    entity_id: binary_sensor.contact_sensor_3
#    id: gym_door
#    device_class: door
#  - platform: homeassistant
#    entity_id: binary_sensor.server_door
#    id: server_door
#    device_class: door
#  - platform: homeassistant
#    entity_id: binary_sensor.contact_sensor_2
#    id: main_door
#    device_class: door

sensor:
  # Kitchen
  - platform: homeassistant
    entity_id: sensor.kitchen_temperature
    id: kitchen_temp
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.kitchen_humidity
    id: kitchen_hum

  # Living Room
  - platform: homeassistant
    entity_id: sensor.living_room_temperature
    id: livingroom_temp
  - platform: homeassistant
    entity_id: sensor.living_room_humidity
    id: livingroom_hum    

  # Master Bedroom
  - platform: homeassistant
    entity_id: sensor.master_bedroom_temperature
    id: mastbed_temp
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.master_bedroom_humidity
    id: mastbed_hum    

  # Guest Bedroom
  - platform: homeassistant
    entity_id: sensor.guest_bedroom_temperature
    id: guestbed_temp
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.guest_bedroom_humidity
    id: guestbed_hum  

  # AL Studio
  - platform: homeassistant
    entity_id: sensor.al_studio_temperature
    id: alstudio_temp
  - platform: homeassistant
    entity_id: sensor.al_studio_humidity
    id: alstudio_hum  

  # LG Studio
  - platform: homeassistant
    entity_id: sensor.lg_studio_temperature
    id: lgstudio_temp
    on_value:
      then:
      - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.lg_studio_humidity
    id: lgstudio_hum  

  # Attic
  - platform: homeassistant
    entity_id: sensor.zigbee_21602_1_1_temperature
    id: attic_temp
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.zigbee_21602_1_1_zigbee_21602_1_2_relative_humidity
    id: attic_hum

  # Server
  - platform: homeassistant
    entity_id: sensor.server_temp_temperature
    id: server_temp
    on_value:
      then:
      - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.server_hum_relative_humidity
    id: server_hum

  - platform: homeassistant
    entity_id: sensor.grange_wind
    id: windnow

  - platform: homeassistant
    entity_id: sensor.openweathermap_temperature
    id: tempnow
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - platform: homeassistant
    entity_id: sensor.sun_next_rising
    id: sunrising

  - platform: homeassistant
    entity_id: sensor.sun_next_setting
    id: sunsetting

  - platform: homeassistant
    entity_id: sensor.grange_thunderstorm_probability_day_0d
    id: stormd0
  - platform: homeassistant
    entity_id: sensor.grange_thunderstorm_probability_day_1d
    id: stormd1
  - platform: homeassistant
    entity_id: sensor.grange_thunderstorm_probability_day_2d
    id: stormd2

  # Create sensors for monitoring cartaccia remotely.
  - platform: template
    name: "Carta - Display Last Update"
    device_class: timestamp
    entity_category: "diagnostic"
    id: display_last_update    

text_sensor:
  - platform: homeassistant
    entity_id: weather.grange_2
    id: weathernow

  - platform: homeassistant
    entity_id: weather.grange_2
    attribute: forecast
    id: accuweatherfore
    internal: yes

  - platform: sun
    type: sunrise
    format: "%H:%M"
    id: sunrise_hour
  - platform: sun
    type: sunset
    format: "%H:%M"
    id: sunset_hour