esphome:
  name: carta-diggitale
  friendly_name: carta diggitale
  on_boot:
    priority: -10
    then:
      - delay: 10s
      - component.update: epaper  

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "runCGvJaVNPxH5nFCPSwxtk61yTmQrFOP2N0UfSJjyk="

ota:
  password: "d914193e08e3fb4f1b8b49738565c234"
  
font:
  - file: 'fonts/Roboto-Regular.ttf'
    id: font_regular
    size: 25
  - file: 'fonts/Roboto-Regular.ttf'
    id: font_regular_75
    size: 75
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '’','(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z','å', 'ä', 'ö', '/','º','µ','³']    
    
  - file: 'fonts/Roboto-Bold.ttf'
    id: font_medium_28
    size: 28

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_30
    size: 45
    glyphs: [
      "", # mdi-thermometer
      "", # mdi-water-percent
      "ﴟ", # mdi-air-filter
      "󰒋", #server
      "󰔏", #temp
      "󰇥" #duck
      ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password    

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14
  id: epaper_display

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/London
    on_time:
      # Every 1 minutes
      - seconds: 0
        then:
          - component.update: epaper

sensor:
  - platform: homeassistant
    entity_id: sensor.zigbee_33983_1_1_temperature
    id: my_temp

  - platform: homeassistant
    entity_id: sensor.kitchen_temperature
    id: my_kitchen_temp

    

binary_sensor:
  - platform: homeassistant
    entity_id: binary_sensor.contact_sensor_3
    id: gym_door
    device_class: door
  - platform: homeassistant
    entity_id: binary_sensor.server_door
    id: server_door
    device_class: door
  - platform: homeassistant
    entity_id: binary_sensor.contact_sensor_2
    id: main_door
    device_class: door

display:
  - platform: waveshare_epaper
    id: epaper  
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    model: 7.50inV2alt
    rotation: 90
    update_interval: 12min
    #reset_duration: 2ms

    lambda: |-
      ESP_LOGI("display", "Updating...");
      // OUTSIDE
      //it.line(0, 0, 100, 50);
    
      //Linee Verticali
      it.line(240, 20, 240, 150);
      it.line(240, 390, 240, 530);
      //Linee Orizzontali
      it.line(20, 270, 140, 270);

      it.line(360, 270, 460, 270);

      it.circle(240, 270, 100);

      it.filled_rectangle(40, 650, 400, 7);


      it.strftime(20, 20 , id(font_regular_75), TextAlign::BASELINE_CENTER, "%H:%M", id(homeassistant_time).now());